config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :users, only: [:new, :create]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/search', to: 'congress#search'
  post '/search_state', to:'congress#index'
  get '/special', to:'special#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :email
  has_secure_password

  enum role: %w[default manager admin]
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :require_admin

  def index

  end

  private

  def require_admin
    redirect_to root_path unless current_admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/congress_controller.rb
class CongressController < ApplicationController

  def index
    # violations: DRY, SRP, abstraction (controller handling all of it), encapsulation (exposing
    # all of the business logic in the controller)

    @members = CongressFacade.members(params[:state])

    render "welcome/index"
  end

  def search
    conn = Faraday.new(url: "https://api.propublica.org") do |faraday|
      faraday.headers["X-API-KEY"] = ENV['govt_api_key']
    end
    response = conn.get("/congress/v1/116/senate/members.json")

    data = JSON.parse(response.body, symbolize_names: true)

    members = data[:results][0][:members]

    found_members = members.find_all {|m| m[:last_name] == params[:search]}
    @member = found_members.first
    render "welcome/index"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome, #{user.email}!"
      redirect_to root_path
    else
      flash[:error] = "Sorry, your credentials are bad."
      render :new
    end
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/controllers/special_controller.rb
class SpecialController < ApplicationController
  before_action :require_user, only: [:index]

  def index
  end

  private

  def require_user
    if !current_user
      redirect_to root_path
      flash[:alert] = 'You must be logged in'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path
      flash[:success] = "Welcome, #{user.email}!"
    else
      redirect_to '/users/new'
      flash[:error] = user.errors.full_messages
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    cookies.encrypted[:secret_message] = "cookies are delicious"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/states_helper.rb
module StatesHelper
  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end

app/views/admin/dashboard/index.html.erb
<h1>ADMIN DASHBOARD!!!!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CongressTracker2108</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end %>

  <%= yield %>
  </body>
</html>

app/views/special/index.html.erb
<h2>Welcome to this special page for only logged in users</h2>

app/views/users/login_form.html.erb
<%= form_with url: login_path, method: :post, local: true do |form| %>
  <%= form.label :email, 'Email:' %>
  <%= form.text_field :email %>
  <%= form.label :password, 'Password:' %>
  <%= form.text_field :password %>
  <%= form.submit 'Log In' %>
<% end %>

app/views/users/new.html.erb
<%= form_with model: @user, local: true do |form| %>
  <%= form.label :name, 'Name' %>
  <%= form.text_field :name %>
  <%= form.label :email, 'Email' %>
  <%= form.text_field :email %>
  <%= form.label :password, 'Password' %>
  <%= form.text_field :password %>
  <%= form.label :password_confirmation, 'Password Confirmation' %>
  <%= form.text_field :password_confirmation %>
  <%= form.submit 'Create User' %>
<% end %>

app/views/welcome/index.html.erb
<% if current_user %>
  <%= link_to "Logout", '/logout', method: :delete %>
<% else %>
  <%= link_to "Register as a User", new_user_path %>
  <%= link_to "Login", login_path %>
<% end %>

<%= form_with url: search_path, local: true do |form| %>
  <%= form.label :search, 'Search For Senators By Last Name:' %>
  <%= form.text_field :search %>
  <%= form.submit 'Search' %>
<% end %>
<%= form_with url: search_state_path, local: true do |form| %>
  <%= form.label :search_state, 'Search For House Members Of A Specific State' %>
  <%= form.select :state, us_states %>
  <%= form.submit 'Search By State' %>
<% end %>
<% if @member %>
  <h5>Senator <%= @member.first_name.concat(" ").concat(@member.last_name) %> was found! Their twitter
    is: <%= @member.twitter_account %></h5>
<% end %>

<% if @members %>
  <h1><%= @members.size %> Results </h1>
  <% @members.each do |house_member| %>
    <ul class="house_members">
      <li class="name"><%= house_member.name %></li>
      <li class="role"><%= house_member.role %></li>
      <li class="party"><%= house_member.party %></li>
      <li class="district"><%= house_member.district %></li>
    </ul>
  <% end %>
<% end %>